[features]
seeds = false
skip-lint = false
[programs.localnet]
crowfunding = "AV2xQYKbkaDdxjS7WLz9TiuRiyWf1Dqva4LPbcUXFFNy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "/home/ncalvo/.config/solana/id.json"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
